---
- name: Update Apt sources
  apt:
    update_cache: yes
  register: apt_update
  until: apt_update | success
  retries: 5
  delay: 2

- name: Install Apt dependencies
  apt:
    pkg: "{{ item }}"
    state: "latest"
  register: install_deps
  until: install_deps | success
  retries: 5
  delay: 2
  with_items: "{{ storm_distro_packages }}"
  when: not skip_install
