---
- name: storm-nimbus | restart | restart storm-nimbus service
  service: name=storm-nimbus state=restarted enabled=yes
  when: monasca_storm_restart_required

- name: storm-nimbus | start | start storm-nimbus service
  service: name=storm-nimbus state=started enabled=yes

- name: storm-ui | restart | restart storm-ui service
  service: name=storm-ui state=restarted enabled=yes
  when: storm_ui_enabled and monasca_storm_restart_required

- name: storm-ui | start | start storm-ui service
  service: name=storm-ui state=started enabled=yes
  when: storm_ui_enabled

- name: wait for nimbus port
  wait_for: port={{nimbus_thrift_port}} state=started timeout={{ monasca_wait_for_period }}
  when: verify

- name: wait for ui port
  wait_for: port={{storm_ui_port}} state=started timeout={{ monasca_wait_for_period }}
  when: storm_ui_enabled and verify
